config/routes.rb
Rails.application.routes.draw do

  patch 'adminsters/users/:user_id/orders/:id' => 'orders#update', as: "user_order"
  
  devise_for :adminsters
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :items
  resources :orders, only:[:create,:show, :index]
  resources :order_items
  resources :carts, only: [:show,:create,:update,:destroy]
  resources :users, only: [:show, :edit, :update, :index, :destroy]
  resources :adminsters, only: [:show, :update]

  get '/adminsters/users/:id' => 'adminsters#show_user', as: "adminsters_show_user"
  get '/adminsters/users' => 'adminsters#manage_users', as: "adminsters_manage_users"
  get '/adminsters/user/:id/edit(.:format)' => 'adminsters#edit_user_details', as: "adminsters_edit_user_details"
  delete 'adminsters/users/:id' => 'adminsters#destroy', as: "destroy_user"

  root "top#index"
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
  	@items = Item.page(params[:page]).per(8)
  	@cart = Cart.new
  	if params[:search].present?
		@items = @items.get_all params[:search]
	end

  end
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/top/index.html.erb
<head>
  <title>Top#index</title>
</head>


<body>
<div class="text-center">
<%= paginate @items %>
</div>

<div class="container">
      <% if flash[:notice] %>
          <p id="notice">
            <%= flash[:notice] %>
          </p>
        <% end %>
  <div class="row">
      <% @items.each do |item| %>
        <div class="col-sm-3 row-eq-height">
          <%= form_for(@cart) do |f| %>
            <div class="panel panel-primary">
              <%= f.hidden_field :item_id, value: item.id %>
              <div class="panel-heading panel-size">
                <h4><%= item.album_name %></h4>
                <br>
                <%= item.artist_name %>
              </div>
              <div class="panel-body">
                <% if item.cd_image.nil? %>
                  <%= image_tag 'no_image.jpg', class:"img-responsive" %>
              <% else %>
                  <%= link_to item_path(item) do %><%= attachment_image_tag(item, :cd_image, class:"img-responsive")%><%end%>
                <% end %>
              </div>
              <div class="panel-footer">
                価格 | ¥<%= item.price.to_s(:delimited)%>
                <% if user_signed_in? %>
                  <%= f.select :quantity, [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30], class: "quantity-form" %>
                  <div class="pull-right" "btn btn-default" aria-hidden="true">
                    <%= f.submit "カート",class: "btn, btn-primary pull-right" %>
                  </div>
                <% else %>
                <% end %>
                </div>
            </div>
          <% end %>
        </div>
    <% end %>
  </div>
</div>

<div class="text-center">
<%= paginate @items %>
</div>

<br><br>

</body>