config/routes.rb
Rails.application.routes.draw do

  patch 'adminsters/users/:user_id/orders/:id' => 'orders#update', as: "user_order"
  
  devise_for :adminsters
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :items
  resources :orders, only:[:create,:show, :index]
  resources :order_items
  resources :carts, only: [:show,:create,:update,:destroy]
  resources :users, only: [:show, :edit, :update, :index, :destroy]
  resources :adminsters, only: [:show, :update]

  get '/adminsters/users/:id' => 'adminsters#show_user', as: "adminsters_show_user"
  get '/adminsters/users' => 'adminsters#manage_users', as: "adminsters_manage_users"
  get '/adminsters/user/:id/edit(.:format)' => 'adminsters#edit_user_details', as: "adminsters_edit_user_details"
  delete 'adminsters/users/:id' => 'adminsters#destroy', as: "destroy_user"

  root "top#index"
end

app/models/adminster.rb
class Adminster < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :items

end

app/controllers/adminsters_controller.rb
class AdminstersController < ApplicationController
	before_action :authenticate_adminster!

	def top
		@items = Item.all
	end

	def manage_users
		@users = User.all
		@users = @users.get_all params[:search]
	end

	def show
		@users = User.all
		if params[:search].present?
			@users = @users.get_all params[:search]
		end
		# @user = User.find(params[:id])
	end

	def show_user
		@user = User.find(params[:id])
		@orders = @user.orders.page(params[:page]).reverse_order
	end

	def edit_user_details
		@user = User.find(params[:id])
	end

	def update
		@user = User.find(params[:id])
		if @user.update(user_params)
        	redirect_to adminsters_manage_users_path, notice: "更新しました。"
        else
        	render 'edit_user_details'
        end
	end


	def destroy
		user = User.find(params[:id])
        user.update_attribute(:leave, false)
        redirect_to adminsters_manage_users_path
	end

	def user_params
		params.require(:user).permit(:first_name, :last_name, :first_name_kana, :last_name_kana, :post_code, :address, :phone, :leave, :update_at, :email)
	end

	

end

app/helpers/adminsters_helper.rb
module AdminstersHelper
end

app/views/adminsters/edit_user_details.html.erb
<body>
  <% if flash[:alert] %>
  <div class="alert alert-danger">
    <%= flash[:alert] %>
  </div>
  <% end %>

  <div class="container">
   <h2>個人情報の編集</h2>
   <div class="row">
     <div class="col-sm-12 col-md-3">
     </div>

     <div class="col-sm-12 col-md-9">
       <%# if @user.id == current_user.id %>
       <%= form_for(@user,url: adminster_path) do |f| %>

       <% if @user.errors.any? %>
       <div id="error_explanation">
        <h2><%= @user.errors.count %>件のエラーがあります。</h2>

        <ul>
          <%= @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
          <% end %>
        </ul>
      </div>
      <% end %>


      <!-- 個人情報 -->
      <div class="field has-success">
        <%= f.label :last_name, "苗字:" %><br>
        <%= f.text_field :last_name, class: "form-control" %>
      </div>
      <div class="field has-success">
        <%= f.label :last_name_kana, "苗字(カナ):" %><br>
        <%= f.text_field :last_name_kana, class: "form-control" %>
      </div>
      <div class="field has-success">
        <%= f.label :first_name, "名前:" %><br>
        <%= f.text_field :first_name, class: "form-control" %>
      </div>
      <div class="field has-success">
        <%= f.label :first_name_kana, "名前(カナ):" %><br>
        <%= f.text_field :first_name_kana, class: "form-control" %>
      </div>
      <div class="field has-success">
        <%= f.label :post_code, "郵便:" %><i>　例）1234567(ハイフン無し)</i><br>
        <%= f.text_field :post_code, class: "form-control" %>
      </div>
      <div class="field has-success">
        <%= f.label :address, "住所:" %><br>
        <%= f.text_field :address, class: "form-control" %>
      </div>
      <div class="field has-success">
        <%= f.label :phone, "電話:" %><i> 例）01234567890(ハイフン無し)</i><br>
        <%= f.text_field :phone, class: "form-control" %>
      </div>
      <div class="field has-success">
        <%= f.label :email, "メールアドレス:" %><br>
        <%= f.email_field :email, class: "form-control" %>
      </div>
      <%#= f.hidden_field :password,value: @user.password %>
      <%#= f.hidden_field :password_confirmation,value: @user.password %>


      <br>

      <!-- 個人情報更新するボタン -->
      <div class="actions">
        <%= f.submit"更新", class:"btn btn-lg btn-block btn-info" %>
        <% end %>

      </div>
    </div>
  </div>



</div><br><br>
</body>

app/views/adminsters/manage_users.html.erb
<div class="container-fluid">

	<div class="row">
		<div class="col-xs-offset-2 col-xs-8 panel panel-default">
			<h2> 会員情報</h2>
			<div>
				<table class="table table-hover">
					<thead>
						<tbody>
						<tr>
							<th style="width:200px;">お名前</th>
							<td>
								<%= @user.last_name %>
								<%= @user.first_name %>
							</td>
						</tr>
						<tr>
							<th>ふりがな</th>
							<td>
								<%= @user.last_name_kana %>
								<%= @user.first_name_kana %>
							</td>
						</tr>
						    <th>ご住所</th>
							<td>
								<%= @user.post_code %>
								<%= @user.address %>
							</td>
						</tr>
						<tr>
							<th>電話番号</th>
							<td>
								<%= @user.phone %>
							</td>
						</tr>
						<tr>
							<th>メールアドレス</th>
							<td>
							    <%= @user.email %>
							</td>
						</tr>
						<tr>
							<th>パスワード</th>
							<td>
								*******
								<i> 　※セキュリティのためパスワードは非表示となっています。</i>
							</td>
						</tr>
					</tbody>
					</thead>
				</table>
			</div>
		</div>
			<div class="col-xs-offset-2 col-xs-8">
				<div class="pull-right">
					<%= link_to ' 登録内容の編集', edit_user_path(current_user), class: 'btn btn-default glyphicon glyphicon-cog' %>
					<%= link_to '退会する', user_path, class: 'btn btn-default', method: :delete, data: { confirm: "本当に退会しますか…？" } %>
 				</div>
		    </div>
    </div>

	<div class="row">
		<% @orders.each do |order| %>
			<div class="col-xs-offset-2 col-xs-8 panel panel-default">
				<h2> 購入履歴</h2>
				<div class="row">
					<div class="col-xs-4">
						<h4>購入日</h4>
							<p><%= order.created_at.strftime('%Y年%m月%d日 %H:%M') %></p>
						<h4>購入者</h4>
						<p>
							<%= order.billing_first_name %>
							<%= order.billing_last_name %>
						</p>
						<h4>送付先</h4>
						<p>
							<%= order.billing_post_code %>  
							<%= order.billing_address %>
						</p>
						<h4>ステータス</h4>
						<p>
							<%= order.status %>
						</p>
					</div>
					<div class="col-xs-6">
		    <% order.order_items.each do |order_item| %>
					　　<table class="table">
						　　<thead>
							<tr>
								<td>
									<div class="img"><%= attachment_image_tag order_item.item, :cd_image, class: "img-thumbnail cdcover", fallback: "no_image.jpg" %></div>
								</td>
								<td colspan="3">
									<%= order_item.item.album_name %><br>
									購入枚数: <%= order_item.quantity %> 枚<br>
									小計 <%= order_item.item.price.to_s(:delimited) %> 円
								</td>
							</tr>
						    </thead>
					    </table>
			<% end %>
					</div>
					<div class="col-md-12">
						<p class="text-right"><span style="font-size: 20px;">合計　<%= order.total.try(:to_s, :delimited) %> 円</span></p>
					</div>
				</div>

			</div>
	    <% end %>
	</div>
	<div class="text-center">
	<%= paginate @orders, class: "pagenate" %>
    </div>
</div>

app/views/adminsters/show.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-12">
			<h2 class="col-md-3 col-md-offset-5">ユーザー一覧</h2>
			<div class="title col-md-12"></div>
		</div>
	</div>

	<div class="row col-md-12">
		<%= form_tag(adminsters_manage_users_path, method: "get") do %>
			<%= text_field_tag :search, params[:search], class: "searchbar col-md-8 col-md-offset-2", placeholder: "検索..." %>
			<%= submit_tag "検索", class: "btn btn-success" %>
		<% end %>
	</div>

	<div class="row">
		<table class="table table-hover">
			<thead>
				<tr>
					<th class="center">ユーザー名</th>
					<th class="center">メール</th>
					<th class="center">郵便番号</th>
					<th class="center">住所</th>
					<th class="center" >電話番号</th>
					<th class="center" >存在</th>
					<th class="center" colspan="3">アクション</th>
				</tr>
			</thead>
			<tbody>
				<% @users.each do |user| %>
				<tr>
					<td class="center">
						<ruby>
							<%= user.last_name%>
							<%= user.first_name %> 							
								<rt> 
									<%= user.last_name_kana %> 
									<%= user.first_name_kana %>
								</rt>
						</ruby>
					</td>
					<td class="center"><%= user.email %></td>
					<td class="center"><%= user.post_code %></td>
					<td class="center"><%= user.address %></td>
					<td class="center"><%= user.phone %></td>
					<td class="center"><%= user.leave %></td>
					<td><%= link_to adminsters_show_user_path(user) do %><i class="fa fa-window-maximize" aria-hidden="true"></i><% end%></td>
					<td><%= link_to adminsters_edit_user_details_path(user) do %><i class="fa fa-pencil" aria-hidden="true"></i><% end %></td>
					<td><%= link_to destroy_user_path(user), method: :delete, "data-confirm" => "Are you sure?" do %><i class="fa fa-trash-o" aria-hidden="true"></i><% end %></td>
				</tr>
				<%end%>
			</tbody>
		</table>
	</div>
</div>

app/views/adminsters/show_user.html.erb
<div class="container-fluid">

	<div class="row">
		<div class="col-xs-offset-2 col-xs-8 panel panel-default">
			<h2> 会員情報</h2>
			<div>
				<table class="table table-hover">
					<thead>
						<tbody>
						<tr>
							<th style="width:200px;">お名前</th>
							<td>
								<%= @user.last_name %>
								<%= @user.first_name %>
							</td>
						</tr>
						<tr>
							<th>ふりがな</th>
							<td>
								<%= @user.last_name_kana %>
								<%= @user.first_name_kana %>
							</td>
						</tr>
						    <th>ご住所</th>
							<td>
								<%= @user.post_code %>
								<%= @user.address %>
							</td>
						</tr>
						<tr>
							<th>電話番号</th>
							<td>
								<%= @user.phone %>
							</td>
						</tr>
						<tr>
							<th>メールアドレス</th>
							<td>
							    <%= @user.email %>
							</td>
						</tr>
						<tr>
							<th>パスワード</th>
							<td>
								*******
								<i> 　※セキュリティのためパスワードは非表示となっています。</i>
							</td>
						</tr>
					</tbody>
					</thead>
				</table>
			</div>
		</div>
			<div class="col-xs-offset-2 col-xs-8">
				<div class="pull-right">
					<%= link_to ' 登録内容の編集', adminsters_edit_user_details_path, class: 'btn btn-default glyphicon glyphicon-cog' %>
					<%= link_to '退会させる', adminsters_show_user_path, class: 'btn btn-default', method: :delete, data: { confirm: "退会させてよろしいでしょうか？" } %>
 				</div>
		    </div>
    </div>

	<div class="row">
		<% @orders.each do |order| %>
			<div class="col-xs-offset-2 col-xs-8 panel panel-default">
				<h2> 購入履歴</h2>
				<div class="row">
					<div class="col-xs-4">
						<h4>購入日</h4>
							<p><%= order.created_at.strftime('%Y年%m月%d日 %H:%M') %></p>
						<h4>購入者</h4>
						<p>
							<%= order.billing_last_name %>
							<%= order.billing_first_name %>
						</p>
						<h4>送付先</h4>
						<p>
							<%= order.billing_post_code %>
							<%= order.billing_address %>
						</p>
						<h4>ステータス</h4>
						<p>
							<%= form_for(Order.new, url: user_order_path(@user, order), method: :patch) do |f| %>
							  <%=  f.select :status, Order.statuses.keys, selected: order.status %>
							  <%= f.submit "更新", class: "btn btn-success btn-xs" %>
							<% end %>
						</p>
					</div>
					<div class="col-xs-6">
		    <% order.order_items.each do |order_item| %>
					　　<table class="table">
						　　<thead>
							<tr>
								<td>
									<div class="img"><%= attachment_image_tag order_item.item, :cd_image, class: "img-thumbnail cdcover", fallback: "no_image.jpg" %></div>
								</td>
								<td colspan="3">
									<%= order_item.item.album_name %><br>
									購入枚数: <%= order_item.quantity %> 枚<br>
									小計 <%= order_item.item.price.to_s(:delimited) %> 円
								</td>
							</tr>
						    </thead>
					    </table>
			<% end %>
					</div>
					<div class="col-md-12">
						<p class="text-right"><span style="font-size: 20px;">合計　<%= order.total.try(:to_s, :delimited) %> 円</span></p>
					</div>
				</div>

			</div>
	    <% end %>
	</div>
	<div class="text-center">
	<%= paginate @orders, class: "pagenate" %>
    </div>
</div>