config/routes.rb
Rails.application.routes.draw do

  patch 'adminsters/users/:user_id/orders/:id' => 'orders#update', as: "user_order"
  
  devise_for :adminsters
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :items
  resources :orders, only:[:create,:show, :index]
  resources :order_items
  resources :carts, only: [:show,:create,:update,:destroy]
  resources :users, only: [:show, :edit, :update, :index, :destroy]
  resources :adminsters, only: [:show, :update]

  get '/adminsters/users/:id' => 'adminsters#show_user', as: "adminsters_show_user"
  get '/adminsters/users' => 'adminsters#manage_users', as: "adminsters_manage_users"
  get '/adminsters/user/:id/edit(.:format)' => 'adminsters#edit_user_details', as: "adminsters_edit_user_details"
  delete 'adminsters/users/:id' => 'adminsters#destroy', as: "destroy_user"

  root "top#index"
end

app/models/item.rb
class Item < ApplicationRecord
	belongs_to :adminster
    has_many :order_items
    has_many :discs, :dependent => :destroy
	has_many :tracks, :dependent => :destroy
	attachment :image

	has_many :carts

	attachment :cd_image


	#scope :get_by_album_name, ->(album_name){ where( "album_name like ?", "%#{album_name}%" )}
	#scope :get_by_artist_name, ->(artist_name) { where("artist_name like ?", "%#{artist_name}%" )}
	#scope :get_by_artist_name_kana, ->(artist_name_kana) { where("artist_name_kana like ?", "%#{artist_name_kana}

	scope :get_all, ->(search) { where(Item.arel_table[:album_name].matches("%#{search}%").or(Item.arel_table[:artist_name_kana].matches("%#{search}%").or(Item.arel_table[:artist_name].matches("%#{search}%")))) }
	
	scope :active, -> {where(deleted:false)}
   
	accepts_nested_attributes_for :discs, allow_destroy: true

	validates :cd_image,
			  :album_name,
			  :artist_name,   
			  :label_name, 
			  :genre, 
			  :stock, 
			  :luanch_date, 
			  :editor, 
			  :item_status,  
			  				presence: true

	validates :artist_name_kana, 
			 				format:{ with: /[\p{katakana}　ー－&&[^ -~｡-ﾟ]]+/, 
						    message: '全角カナで入力して下さい' }
	validates :price, 
					numericality: { greater_than_or_equal_to: 1, only_integer: true} 

	# validates :cd_image, 
	# 				format: { with: %r{\.(gif|jpg|png)\Z}i,
	# 				message: 'gif,png,jpgファイルをアップロートしてください'}

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
	before_action :authenticate_adminster!, only: [:new, :create, :edit, :update, :destroy]
	def new
		@item = Item.new
		1.times do
			disc = @item.discs.build
		 		1.times{ disc.tracks.build }
		end
	end

	def create
		@item = Item.new(item_params)
		@item.adminster_id = current_adminster.id
		if @item.save
			redirect_to items_path
		else
			render :new
		end
	end

	def edit
		@item = Item.find(params[:id])
		0.times do
			disc = @item.discs.build
		 		0.times{ disc.tracks.build }
		 end
	end

	def update
		@item = Item.find(params[:id])
		@item.adminster_id = current_adminster.id
		if @item.update(item_params)
			redirect_to item_path
		else
			render :template => "items/edit"
		end
	end

	def destroy
		@item = Item.find(params[:id])
		@item.update_attribute(:active, false)
		redirect_to items_path
	end

	def index
		@items = Item.all
		if params[:search].present?
			@items = @items.get_all params[:search]
		end
	end

	def show
		@item = Item.find(params[:id])
		@cart = Cart.new
	end

	private
	def item_params
	  params.require(:item).permit(:adminster_id, 
	  							   :artist_name, 
	  							   :artist_name_kana, 
	  							   :album_name, 
	  							   :price, 
	  							   :label_name, 
	  							   :genre, 
	  							   :cd_image, 
	  							   :stock, 
	  							   :luanch_date, 
	  							   :editor, 
	  							   :item_status,
	  							   discs_attributes: [:id, 
	  							   					  :disc_number, 
	  							   					  :disc_name, 
	  							   					  :_destroy,
	  							   					  tracks_attributes: [:id, 
	  							   					  					  :track_number, 
	  							   					  					  :track_name, 
	  							   					  					  :artist_name, 
	  							   					  					  :_destroy
	  							   					  					  ]
	  							   					  ]
	  							   	)
	end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_disc_fields.html.erb
<div class="row">
<fieldset class="grey">
	<div class="col-md-12">
		<%= f.label :name, "ディスク" %>
		<%= f.hidden_field :_destroy %>
		<%= link_to '#', class: "remove_fields" do%><span class="glyphicon glyphicon-trash trash"></span><% end %>
	</div>
	
	<div class="col-md-1 addsong"><%= f.select :disc_number, ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10'], :prompt => '番号' %></div>

	<div class="col-md-11">
	<%= f.text_field :disc_name, placeholder: "ディスク名", class: "form-control" %>
	</div>

	<!--曲の増加-->
	<div class="col-md-12">
		<%= f.fields_for :tracks do |builder| %>
			<%= render "track_fields", f: builder %>
		<% end %>
		<%= link_to_add_fields "＋", f, :tracks, class: "btn btn-primary btn-sm plusbtn" %>					
	</div>

</fieldset>
</div>

app/views/items/_form.html.erb
<div class="container">
	<div class="row">
		<%= form_for(@item) do |f| %>

		<!--error message-->
		<% if @item.errors.any? %>
			<div class="error_amount col-md-5 col-md-offset-4"><h4><%= @item.errors.count %>件のエラーが発生しました！</h4></div>
			<div id="error_explanation" class="col-md-5 col-md-offset-4">
			    	<% @item.errors.full_messages.each do |message| %>
			        	<li><%= message %></li>
			    	<% end %>
			</div>
   		 <% end %>



		<div class="col-md-4">
			<div class="form-group">
				<%= f.label :cd_image, "カーバー" %>
				<%= f.attachment_field :cd_image, placeholder: "画像", class: "user-edit-form" %>
				<%= attachment_image_tag @item, :cd_image, class: "img-thumbnail cdcover", fallback: "no_image.jpg"%>
			</div>
		</div>
		<div class="col-md-8">
			<div class="col-md-12">
				<div class="form-group">
				  <%= f.label :album_name, "アルバム名" %>
				  <%= f.text_field :album_name, class: "form-control" %>
				</div>
			</div>

			<div class="col-md-12">
				<div class="form-group">
				  <%= f.label :artist_name, "アーティスト名" %>
				  <%= f.text_field :artist_name, class: "form-control" %>
				</div>
			</div>

			<div class="col-md-12">
				<div class="form-group">
				  <%= f.label :artist_name_kana, "アーティスト名(全角カナ)" %>
				  <%= f.text_field :artist_name_kana, class: "form-control" %>
				</div>
			</div>

			<div class="col-md-12">
			  <div class="form-group">
		  		<%= f.label :label_name, "レーベル名" %>
		  		<%= f.text_field :label_name, class: "form-control" %>
		  	  </div>
		  	</div>

		  	<div class="col-md-12">
		  	  <div class="form-group">
		    	<%= f.label :genre, "ジャンル" %><br>
		    	<%= f.select :genre, ['ミュージック', 'ロック', 'POP', 'ジャズ・フュージョン', 'アニメ・ゲーム', 'クラシック', 'ソウル・R&B'], :prompt => 'Select One' %>
	          </div>
		  	</div>

		  	<div class="col-md-12">
		  	  <div class="form-group">
            	<%= f.label :luanch_date, "発行日" %><br>
            	<%= f.date_select :luanch_date, start_year: Date.current.year-100, end_year: Date.current.year %>
              </div>
		  	</div>

		  	<div class="col-md-12">
			  <div class="form-group">
		  		<%= f.label :stock, "在庫数" %>
		  		<%= f.number_field :stock, class: "form-control" %>
		  	  </div>
		  	</div>

		  	<div class="col-md-12">
			  <div class="form-group">
		  		<%= f.label :price, "価格" %>
		  		<%= f.number_field :price, class: "form-control" %>
		  	  </div>
		  	</div>

		  	<div class="col-md-12">
			  <div class="form-group">
		  		<%= f.label :item_status, "販売状況" %><br>
		  		<%= f.radio_button :item_status, "0" %> 発売前
				<%= f.radio_button :item_status, "1" %>  販売中
				<%= f.radio_button :item_status, "2" %>  売り切れ
		  	  </div>
		  	</div>

		  	<div class="col-md-12">
	            <div class="form-group">
					 <%= f.fields_for :discs do |builder| %>
					 	<%= render "disc_fields", f: builder %>
					 <% end %>
					 <%= link_to_add_fields "ディスク追加", f, :discs, class: "btn btn-primary btn-sm adddisc" %>
	            </div>
        	</div>


		  	<div class="col-md-4">
			  <div class="form-group">
		  		<%= f.label :editor, "編集者" %>
		  		<%= f.text_field :editor, class: "form-control", value: current_adminster.name %>

		  	  </div>
		  	</div>
			
			<div class="col-md-12">
			<%= f.submit "保存", class: "btn, btn-success" %>
			</div>
		</div>
		<%end%>
	</div>
</div>
<br>
<br>

app/views/items/_track_fields.html.erb
<fieldset class="track">
	<div class="col-md-1 addsong"><%= f.select :track_number, ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23', '24', '25', '26', '27', '28', '29', '30'], :prompt => '番号' %></div>
	<div class="col-md-3"><%= f.text_field :artist_name, placeholder: "アーティスト名", class: "form-control" %></div>
    <div class="col-md-7"><%= f.text_field :track_name, placeholder: "曲名", class: "form-control" %></div>

	
	<%#= link_to "ー", '#', class: "remove_fields btn btn-danger btn-sm"%>
	<%= f.hidden_field :_destroy %> 
	<%= link_to '#', class: "remove_fields btn btn-danger" do%>ー<% end %>

</fieldset>

app/views/items/edit.html.erb
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
<div class="container">
	<div class="row">
		<div class="col-md-12">
			<h1 class="col-md-2 col-md-offset-5">商品編集</h1>
		</div>
		<div class="title col-md-12"></div>
	</div>
</div>

<%= render 'form' %>


<div class="container">
	<div class="row">
		<div class="col-md-offset-4 btn-delete">
		<%= link_to item_path(@item), class: "btn btn-danger btn-block", method: :delete, "data-confirm" => "Are you sure?" do %>商品を削除する<% end %>
		</div>
	</div>
</div>

app/views/items/index.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-12">
			<h1 class="col-md-2 col-md-offset-5">商品一覧</h1>
			<div class="title col-md-12"></div>
		</div>
	</div>

	<div class="row col-md-12">
		<%= form_tag(items_path, method: "get") do %>
			<%= text_field_tag :search, params[:search], class: "searchbar col-md-8 col-md-offset-2", placeholder: "検索..." %>
			<%= submit_tag "検索", class: "btn btn-success" %>
		<% end %>
	</div>

	<div class="row">
		<table class="table table-hover">
			<thead>
				<tr>
					<th class="center">アルバム名</th>
					<th class="center">アーティスト名</th>
					<th class="center">ジャンル</th>
					<th class="center">販売日</th>
					<th class="center">在庫数</th>
					<th class="center" >販売状況</th>
					<th class="center">価格</th>
					<th class="center">存在</th>
					<th colspan="3">アクション</th>
				</tr>
			</thead>
			<tbody>
				<% @items.each do |item| %>
				<tr>
					<td class="center"><%= item.album_name %></td>
					<td class="center">
						<ruby>
							<%= item.artist_name %> 
								<rt><%= item.artist_name_kana %></rt>
						</ruby>
					</td>
					<td class="center"><%= item.genre %></td>
					<td class="center"><%= item.luanch_date.strftime('%Y/%m/%d') %></td>
					<td class="center"><%= item.stock %></td>
					<td class="center"><%= item.item_status %></td>
					<td class="center">¥ <%= item.price.to_s(:delimited) %></td>
					<td class="center"><%= item.active %></td>
					<td><%= link_to item_path(item) do %><i class="fa fa-window-maximize" aria-hidden="true"></i><% end%></td>
					<td><%= link_to edit_item_path(item) do %><i class="fa fa-pencil" aria-hidden="true"></i><% end %></td>
					<td><%= link_to item_path(item), method: :delete, "data-confirm" => "Are you sure?" do %><i class="fa fa-trash-o" aria-hidden="true"></i><% end %></td>
				</tr>
				<%end%>
			</tbody>
		</table>
	</div>
</div>

app/views/items/new.html.erb
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
<div class="container">
	<div class="row">
		<div class="col-md-12">
			<h1 class="col-md-2 col-md-offset-5">新規商品</h1>
		</div>
		<div class="title col-md-12"></div>
	</div>
</div>
<%= render 'form' %>

app/views/items/show.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-12">
			<h1 class="col-md-6 col-md-offset-4"><%= @item.album_name %></h1>
		</div>
		<div class="title col-md-12"></div>
	</div>

	<div class="row">
		<div class="col-md-4">
			<%= attachment_image_tag @item, :cd_image, class: "img-thumbnail cdcover", fallback: "no_image.jpg"%>
		</div>
		<div class="col-md-8">
			<div class="col-md-12">
			<%= form_for(@cart) do |f| %>
			   <%= f.hidden_field :item_id, value: @item.id %>
				<h4>アーティスト：<ruby>
									<%= @item.artist_name %><rt><%= @item.artist_name_kana %></rt>
								</ruby>
				</h4>
				<h4>ジャンル：<%= @item.genre %></h4>
				<h4>ラーベル: <%= @item.label_name %></h4>
				<h4>販売日：<%= @item.luanch_date.strftime('%Y年%m月%d日') %></h4>
				<h4>在庫数：<%= @item.stock %> 個</h4>
				<h4>¥ <%= @item.price.to_s(:delimited) %></h4>
			<% if user_signed_in? %>
				<%= f.select :quantity, [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30], class: "quantity-form" %>
				<%= button_tag type: 'submit', class: "btn btn-primary" do %>
				<i class="fa fa-shopping-cart" aria-hidden="true"></i>　カート
				<% end %>
			<%end%>
			 <% end %>

			</div>
		</div>
	</div>
	<div class="row space">
	</div>
	<div class="row"> 
		<div class="col-md-12">
		<% for disc in @item.discs %>			
			<table class="table col-md-8">
				<thead>
					<tr>
						<th class="table-header center" colspan="3">ディスク<%= disc.disc_number%>&nbsp;&nbsp;&nbsp;&nbsp;<%= disc.disc_name %></th>
					</tr>
					<tr>
						<th class="col-md-4 center">番号</th>
						<th class="col-md-4 center">歌手</th>
						<th class="col-md-4 center">曲名</th>
					<tr>
				</thead>
				<tbody>
					<% for track in disc.tracks %>
						<tr>
								<td class="center"><%= track.track_number %></td>
								<td class="center"><%= track.artist_name %></td>
								<td class="center"><%= track.track_name %></td>		
						</tr>
					<% end %>		
				</tbody>
			</table>
		<% end%>
		</div>
	</div>
</div>