config/routes.rb
Rails.application.routes.draw do

  patch 'adminsters/users/:user_id/orders/:id' => 'orders#update', as: "user_order"
  
  devise_for :adminsters
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :items
  resources :orders, only:[:create,:show, :index]
  resources :order_items
  resources :carts, only: [:show,:create,:update,:destroy]
  resources :users, only: [:show, :edit, :update, :index, :destroy]
  resources :adminsters, only: [:show, :update]

  get '/adminsters/users/:id' => 'adminsters#show_user', as: "adminsters_show_user"
  get '/adminsters/users' => 'adminsters#manage_users', as: "adminsters_manage_users"
  get '/adminsters/user/:id/edit(.:format)' => 'adminsters#edit_user_details', as: "adminsters_edit_user_details"
  delete 'adminsters/users/:id' => 'adminsters#destroy', as: "destroy_user"

  root "top#index"
end

app/models/adminster.rb
class Adminster < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :items

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
	include ActiveRecord::Calculations
	belongs_to :item
	belongs_to :user

end

app/models/disc.rb
class Disc < ApplicationRecord
	belongs_to :item
	has_many :tracks, :dependent => :destroy


	accepts_nested_attributes_for :tracks, allow_destroy: true

	default_scope -> {order(disc_number: :asc)}
end

app/models/item.rb
class Item < ApplicationRecord
	belongs_to :adminster
    has_many :order_items
    has_many :discs, :dependent => :destroy
	has_many :tracks, :dependent => :destroy
	attachment :image

	has_many :carts

	attachment :cd_image


	#scope :get_by_album_name, ->(album_name){ where( "album_name like ?", "%#{album_name}%" )}
	#scope :get_by_artist_name, ->(artist_name) { where("artist_name like ?", "%#{artist_name}%" )}
	#scope :get_by_artist_name_kana, ->(artist_name_kana) { where("artist_name_kana like ?", "%#{artist_name_kana}

	scope :get_all, ->(search) { where(Item.arel_table[:album_name].matches("%#{search}%").or(Item.arel_table[:artist_name_kana].matches("%#{search}%").or(Item.arel_table[:artist_name].matches("%#{search}%")))) }
	
	scope :active, -> {where(deleted:false)}
   
	accepts_nested_attributes_for :discs, allow_destroy: true

	validates :cd_image,
			  :album_name,
			  :artist_name,   
			  :label_name, 
			  :genre, 
			  :stock, 
			  :luanch_date, 
			  :editor, 
			  :item_status,  
			  				presence: true

	validates :artist_name_kana, 
			 				format:{ with: /[\p{katakana}　ー－&&[^ -~｡-ﾟ]]+/, 
						    message: '全角カナで入力して下さい' }
	validates :price, 
					numericality: { greater_than_or_equal_to: 1, only_integer: true} 

	# validates :cd_image, 
	# 				format: { with: %r{\.(gif|jpg|png)\Z}i,
	# 				message: 'gif,png,jpgファイルをアップロートしてください'}

end

app/models/order.rb
class Order < ApplicationRecord
    enum status: [ "受付中", "商品準備中", "出荷済" ]

	belongs_to :user
	has_many :order_items

	validates :billing_first_name, :billing_last_name, :billing_first_name_kana, :billing_last_name_kana, :billing_address, presence: true
	validates :billing_post_code, presence: true, format: { with: /\A\d{7}\z/ }
	validates :billing_phone, presence: true, format: { with: /\A\d{10}\z|\A\d{11}\z/ }
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
	belongs_to :order
	belongs_to :item
 
end

app/models/track.rb
class Track < ApplicationRecord
	belongs_to :disc

	default_scope -> {order(track_number: :asc)}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  scope :get_all, ->(search) { where(User.arel_table[:first_name].matches("%#{search}%").or(User.arel_table[:email].matches("%#{search}%").or(User.arel_table[:last_name].matches("%#{search}%").or(User.arel_table[:last_name_kana].matches("%#{search}%").or(User.arel_table[:first_name_kana].matches("%#{search}%")))))) }
  scope :leave, -> {where(deleted:false)}

  validates :first_name, :last_name, :first_name_kana, :last_name_kana, :address, presence: true
  validates :post_code, presence: true, format: { with: /\A\d{7}\z/ }
  validates :phone, presence: true, format: { with: /\A\d{10}\z|\A\d{11}\z/ }
  # validates :password, presence: true

  has_many :carts
  has_many :orders

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
	before_action :authenticate_user!
	def show
		@cart_items = current_user.carts
		@order = Order.new
		@user = current_user
		@user_valid = $user_valid
	end

	def create
		@cart = Cart.new(cart_params)
		@cart.user_id = current_user.id
		@cart.save
		redirect_to cart_path(current_user.id)
	end

	# def update
	# 	@order = current_order
	# 	@cart_item = Cart.find(params[:id])
	# 	@cart_item.update_attributes(cart_params)
	# 	@cart_items = @order.order_items
	# end

	def destroy
		@cart_item = Cart.find(params[:id])
		@cart_item.destroy
		redirect_to cart_path(current_user)
	end

	private
	def cart_params
		params.require(:cart).permit(:item_id, :user_id, :total_price, :quantity)
	end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
	before_action :authenticate_adminster!, only: [:new, :create, :edit, :update, :destroy]
	def new
		@item = Item.new
		1.times do
			disc = @item.discs.build
		 		1.times{ disc.tracks.build }
		end
	end

	def create
		@item = Item.new(item_params)
		@item.adminster_id = current_adminster.id
		if @item.save
			redirect_to items_path
		else
			render :new
		end
	end

	def edit
		@item = Item.find(params[:id])
		0.times do
			disc = @item.discs.build
		 		0.times{ disc.tracks.build }
		 end
	end

	def update
		@item = Item.find(params[:id])
		@item.adminster_id = current_adminster.id
		if @item.update(item_params)
			redirect_to item_path
		else
			render :template => "items/edit"
		end
	end

	def destroy
		@item = Item.find(params[:id])
		@item.update_attribute(:active, false)
		redirect_to items_path
	end

	def index
		@items = Item.all
		if params[:search].present?
			@items = @items.get_all params[:search]
		end
	end

	def show
		@item = Item.find(params[:id])
		@cart = Cart.new
	end

	private
	def item_params
	  params.require(:item).permit(:adminster_id, 
	  							   :artist_name, 
	  							   :artist_name_kana, 
	  							   :album_name, 
	  							   :price, 
	  							   :label_name, 
	  							   :genre, 
	  							   :cd_image, 
	  							   :stock, 
	  							   :luanch_date, 
	  							   :editor, 
	  							   :item_status,
	  							   discs_attributes: [:id, 
	  							   					  :disc_number, 
	  							   					  :disc_name, 
	  							   					  :_destroy,
	  							   					  tracks_attributes: [:id, 
	  							   					  					  :track_number, 
	  							   					  					  :track_name, 
	  							   					  					  :artist_name, 
	  							   					  					  :_destroy
	  							   					  					  ]
	  							   					  ]
	  							   	)
	end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
  	@items = Item.page(params[:page]).per(8)
  	@cart = Cart.new
  	if params[:search].present?
		@items = @items.get_all params[:search]
	end

  end
end

app/helpers/adminsters_helper.rb
module AdminstersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

	def link_to_add_fields(name, f, association, locals={})
		new_object = f.object.send(association).klass.new
		id = new_object.object_id
		fields = f.fields_for(association, new_object, child_index: id) do |builder|
			render(association.to_s.singularize + "_fields", f: builder)
		end
		link_to(name, '#', class: [locals[:class], "add_fields"], data: {id: id, fields: fields.gsub("\n", "")})
	end

end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cosin11</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css'  %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

<body>
    <div class="jumbotron">
          <div class="container text-center">
              <h1>Music Store</h1>
              <p>CD & DVD</p>
          </div>
    </div>

            <header>
                <nav class="navbar navbar-inverse">
                    <div class="collapse navbar-collapse" id="myNavbar">
                      <% if user_signed_in? %>
                      <ul class="nav navbar-nav">
                          <li class="active">
                            <%= link_to ' Home', root_path(current_user.id), class: "glyphicon glyphicon-home" %>
                          </li>
                          <li>
                            <%= link_to ' Mypage', user_path(current_user.id), class: "glyphicon glyphicon-user" %></li>
                          <li>
                            <%= link_to ' Cart list', cart_path(current_user.id), class: "glyphicon glyphicon-home" %>
                            </li>
                          <li>
                            <%= link_to ' logout', destroy_user_session_path, class: "glyphicon glyphicon-log-out" %>
                          </li>
                      </ul>
                      <ul class="nav navbar-nav navbar-right">
                        <li>
                          <p class="navbar-text">ようこそ  <%= current_user.last_name %> <%= current_user.first_name %>  さん！</p>
                        </li>
                        <li>
                          <%= form_tag(root_path, method: "get") do %>
                              <div class="navbar-form navbar-left form-group">
                               <%= text_field_tag :search, params[:search], class: "form-control", placeholder: "商品検索" %>
                               <%= submit_tag "検索", class: "btn btn-default glyphicon glyphicon-search" %>
                               </div>
                            <% end %>
                        </li>
                      </ul>
              </ul>
               <% elsif adminster_signed_in? %>
                     <ul class="nav navbar-nav">
                <li class="active"><%= link_to ' Home', items_path, class: "glyphicon glyphicon-home" %>
                </li>
                <li><%= link_to ' Users', adminsters_manage_users_path, class: "glyphicon glyphicon-user" %>
                </li>
                <li><%= link_to ' logout', destroy_adminster_session_path, class: "glyphicon glyphicon-log-out" %></li>
                <li><%= link_to ' New item', new_item_path, class: "glyphicon glyphicon-star" %></li>
              </ul>
              <ul class="nav navbar-nav navbar-right">
                <li><p class="navbar-text">管理者ページ</p></li>
              </ul>

                      <% else %>

                      <ul class="nav navbar-nav">
                          <li class="active">
                            <%= link_to ' Home', root_path, class: "glyphicon glyphicon-home" %>
                          </li>
                          <li>
                            <%= link_to ' Sign up', new_user_registration_path, class: "glyphicon glyphicon-edit" %>
                          </li>
                          <li>
                            <%= link_to ' Login', new_user_session_path, class: "glyphicon glyphicon-log-in" %>
                          </li>
                      </ul>
                      <ul class="nav navbar-nav navbar-right">
                          <li>
                            <p class="navbar-text">ようこそ ゲスト さん。</p>
                          </li>
                          <li>
                          <%= form_tag(root_path, method: "get") do %>
                              <div class="navbar-form navbar-left form-group">
                               <%= text_field_tag :search, params[:search], class: "form-control", placeholder: "商品検索" %>
                               <%= submit_tag "検索", class: "btn btn-default glyphicon glyphicon-search" %>
                               </div>
                            <% end %>
                          </li>
                      </ul>
                     <% end %>
                    </div>
                </nav>
            </header>

    <%= yield %>

		<footer class="container-fluid text-center">
          <p><%= link_to ' @', new_adminster_session_path %>cosin 11</p>
    </footer>
  </body>
</html>